# Generated by Django 5.0.5 on 2024-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plant_blooming_period_plant_care_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='Environment',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='landscape_use',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AddField(
            model_name='plant',
            name='origin',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='product_description',
            field=models.TextField(default='Not Available'),
        ),
    ]
