# Generated by Django 5.0.5 on 2024-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_cartitem_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='totalprice',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
